### ISSUE TITLE
async / promise support

### ISSUE THREAD

**Issue by jbolda** [sinix-dev/scaffe.js#4]
It would be great if there was an option to have an async version of scaffe. This would remove the need to do the `new Promise` and `resolve(cb())` dance which isn't always the best code structure depending on the situation.

**Comment by sanket143** [comment]
Hey @jbolda thanks for the feedback. I've created a [PR](https://github.com/sinix-dev/scaffe.js/pull/5) to return Promise. Would like to know if that is how you wanted it to be.
